[2024-09-15T09:00:05.279+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T08:00:00+00:00 [queued]>
[2024-09-15T09:00:05.284+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T08:00:00+00:00 [queued]>
[2024-09-15T09:00:05.284+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T09:00:05.285+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2024-09-15T09:00:05.285+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T09:00:05.292+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-15 08:00:00+00:00
[2024-09-15T09:00:05.296+0000] {standard_task_runner.py:55} INFO - Started process 5655 to run task
[2024-09-15T09:00:05.299+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'scheduled__2024-09-15T08:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmpsqe7_81c']
[2024-09-15T09:00:05.299+0000] {standard_task_runner.py:83} INFO - Job 385: Subtask insert_data
[2024-09-15T09:00:05.336+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T08:00:00+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-15T09:00:05.399+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-15T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-15T08:00:00+00:00
[2024-09-15T09:00:05.400+0000] {sql.py:253} INFO - Executing: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Самарская область',
                     '25.31',
                     '25.31',
                     '4',
                     'небольшая облачность'); 
[2024-09-15T09:00:05.404+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T09:00:05.534+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T09:00:05.546+0000] {sql.py:364} INFO - Running statement: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Самарская область',
                     '25.31',
                     '25.31',
                     '4',
                     'небольшая облачность'); , parameters: None
[2024-09-15T09:00:05.551+0000] {sql.py:373} INFO - Rows affected: 1
[2024-09-15T09:00:05.558+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240915T080000, start_date=20240915T090005, end_date=20240915T090005
[2024-09-15T09:00:05.610+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-15T09:00:05.622+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
