[2024-09-15T08:15:18.206+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T05:00:00+00:00 [queued]>
[2024-09-15T08:15:18.230+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T05:00:00+00:00 [queued]>
[2024-09-15T08:15:18.231+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:15:18.231+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2024-09-15T08:15:18.231+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-15T08:15:18.242+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-09-15 05:00:00+00:00
[2024-09-15T08:15:18.253+0000] {standard_task_runner.py:55} INFO - Started process 1959 to run task
[2024-09-15T08:15:18.268+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'save_city_info_weather_v01', 'insert_data', 'scheduled__2024-09-15T05:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/saver_info.py', '--cfg-path', '/tmp/tmprs75274t']
[2024-09-15T08:15:18.270+0000] {standard_task_runner.py:83} INFO - Job 374: Subtask insert_data
[2024-09-15T08:15:18.359+0000] {task_command.py:389} INFO - Running <TaskInstance: save_city_info_weather_v01.insert_data scheduled__2024-09-15T05:00:00+00:00 [running]> on host 0c5fe11d0c9c
[2024-09-15T08:15:18.525+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=save_city_info_weather_v01
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-09-15T05:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-09-15T05:00:00+00:00
[2024-09-15T08:15:18.526+0000] {sql.py:253} INFO - Executing: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Саров',
                     '23.24',
                     '23.24',
                     '2.48',
                     'небольшая облачность'); 
[2024-09-15T08:15:18.544+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:15:18.753+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-09-15T08:15:18.795+0000] {sql.py:364} INFO - Running statement: insert into weathers (city_name, max_temp, min_temp, wind, descript)
            values (
                     'Саров',
                     '23.24',
                     '23.24',
                     '2.48',
                     'небольшая облачность'); , parameters: None
[2024-09-15T08:15:18.801+0000] {sql.py:373} INFO - Rows affected: 1
[2024-09-15T08:15:18.818+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=save_city_info_weather_v01, task_id=insert_data, execution_date=20240915T050000, start_date=20240915T081518, end_date=20240915T081518
[2024-09-15T08:15:18.865+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2024-09-15T08:15:18.905+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
